# Generated by Django 5.1 on 2025-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_userdata_userid_alter_userdata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='userid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
